<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Koh.Opcodes\Koh.Opcodes.csproj" />
    <ProjectReference Include="..\..\Common\Koh.Objects\Koh.Objects.csproj" />
    <ProjectReference Include="..\Koh.Boot\Koh.Boot.csproj" />
    <ProjectReference Include="..\Koh.Emulator\Koh.Emulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Koh.Emulator.App" />
    <InternalsVisibleTo Include="Koh.Debugger.Tests" />
  </ItemGroup>

</Project>
