<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Asm/Koh.Core/Koh.Core.csproj" />
    <ProjectReference Include="../../../src/Common/Koh.Objects/Koh.Objects.csproj" />
    <ProjectReference Include="../../../src/Emulator/Koh.Emulator/Koh.Emulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
