using System.Text;

namespace Koh.Build.Tasks;

/// <summary>
/// PNG tile sheet → Game Boy 2bpp data + CGB palette, emitted as generated C# the game compiles
/// against — the asset pipeline: art is authored as PNG files (checked in, drawn in any editor
/// emitting the constrained subset <see cref="PngReader"/> decodes), never as hand-written byte
/// arrays. A sheet's ≤4 distinct colors become one CGB palette, sorted lightest→index 0 (the
/// conventional GB background shade) by luminance; each 8×8 tile becomes 16 bytes of standard
/// 2bpp bitplanes; the sheet's ACTUAL colors come out as RGB555 constants, so palettes are
/// authored in the PNG too. Per sheet <c>Name</c> (PascalCased file name), the generated
/// <c>static class Art</c> carries <c>NameTiles</c> (ROM byte table), <c>NameTileCount</c>, and
/// <c>NameColor0..3</c>.
/// </summary>
public static class TileSheetConverter
{
    public sealed record Sheet(
        string Name,
        byte[] Tiles,
        int TileCount,
        ushort[] Rgb555Palette // exactly 4 entries, missing colors padded with the darkest
    );

    public static Sheet Convert(string pngPath)
    {
        var name = ToPascalCase(Path.GetFileNameWithoutExtension(pngPath));
        var (width, height, pixels) = PngReader.Decode(pngPath);
        if (width % 8 != 0 || height % 8 != 0 || width == 0 || height == 0)
            throw new InvalidDataException(
                $"'{pngPath}': dimensions {width}x{height} are not a multiple of 8."
            );

        // The sheet's palette: distinct colors, lightest first (index 0 = background shade).
        var colors = pixels.Distinct().ToList();
        if (colors.Count > 4)
            throw new InvalidDataException(
                $"'{pngPath}': {colors.Count} distinct colors (a tile sheet is one 4-color "
                    + "CGB palette)."
            );
        colors.Sort((x, y) => Luminance(y).CompareTo(Luminance(x)));
        var indexOf = new Dictionary<uint, int>();
        for (var i = 0; i < colors.Count; i++)
            indexOf[colors[i]] = i;

        var tilesAcross = width / 8;
        var tilesDown = height / 8;
        var tileCount = tilesAcross * tilesDown;
        var tiles = new byte[tileCount * 16];
        var t = 0;
        for (var ty = 0; ty < tilesDown; ty++)
        for (var tx = 0; tx < tilesAcross; tx++, t++)
        {
            for (var y = 0; y < 8; y++)
            {
                byte low = 0,
                    high = 0;
                for (var x = 0; x < 8; x++)
                {
                    var pixel = pixels[(ty * 8 + y) * width + tx * 8 + x];
                    var index = indexOf[pixel];
                    if ((index & 1) != 0)
                        low |= (byte)(0x80 >> x);
                    if ((index & 2) != 0)
                        high |= (byte)(0x80 >> x);
                }
                tiles[t * 16 + y * 2] = low;
                tiles[t * 16 + y * 2 + 1] = high;
            }
        }

        var palette = new ushort[4];
        for (var i = 0; i < 4; i++)
            palette[i] = Rgb555(colors[Math.Min(i, colors.Count - 1)]);

        return new Sheet(name, tiles, tileCount, palette);
    }

    /// <summary>The generated source for a set of sheets — one <c>static class Art</c> in
    /// <paramref name="namespaceName"/>.</summary>
    public static string GenerateSource(string namespaceName, IReadOnlyList<Sheet> sheets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>Koh tile-sheet pipeline — regenerated from art/*.png");
        sb.AppendLine("// on every build; do not edit.</auto-generated>");
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("static class Art");
        sb.AppendLine("{");
        foreach (var sheet in sheets)
        {
            sb.AppendLine($"    public const byte {sheet.Name}TileCount = {sheet.TileCount};");
            for (var i = 0; i < 4; i++)
                sb.AppendLine(
                    $"    public const ushort {sheet.Name}Color{i} = 0x{sheet.Rgb555Palette[i]:X4};"
                );
            sb.AppendLine($"    public static readonly byte[] {sheet.Name}Tiles =");
            sb.AppendLine("    {");
            for (var i = 0; i < sheet.Tiles.Length; i += 16)
            {
                sb.Append("        ");
                for (var j = 0; j < 16 && i + j < sheet.Tiles.Length; j++)
                    sb.Append($"0x{sheet.Tiles[i + j]:X2}, ");
                sb.AppendLine();
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static double Luminance(uint rgba) =>
        0.2126 * (rgba & 0xFF) + 0.7152 * ((rgba >> 8) & 0xFF) + 0.0722 * ((rgba >> 16) & 0xFF);

    private static ushort Rgb555(uint rgba)
    {
        var r = (int)(rgba & 0xFF);
        var g = (int)((rgba >> 8) & 0xFF);
        var b = (int)((rgba >> 16) & 0xFF);
        return (ushort)(
            ((r * 31 + 127) / 255) | (((g * 31 + 127) / 255) << 5) | (((b * 31 + 127) / 255) << 10)
        );
    }

    private static string ToPascalCase(string fileName)
    {
        var parts = fileName.Split(['-', '_', ' ', '.'], StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part[1..]);
        }
        return sb.ToString();
    }
}
